version: '2.1'

services:
  db:
    image: postgis/postgis:14-master
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgis
      POSTGRES_DB: postgis
      POSTGRES_USER: postgis
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  myapp:
    image: myapp:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080