- name: Deploy application to remote server
  hosts: my_servers
  vars_files:
    - vars.yml
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/Sublimee/dashboard.git'
        dest: "~/dashboard"
        version: master
        depth: 1